app/models.py
from app import db
from flask_login import UserMixin
from app import login

class User(db.Model, UserMixin):
    __tablename__= 'user'
    id=db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    last_name = db.Column(db.String(100))
    email = db.Column(db.String(100),index=True, unique=True)
    password_hash = db.Column(db.String(100))
    todos = db.relationship('Task', backref='owner')

    def __repr__(self) -> str:
        return f'User: {self.name} {self.last_name} - {self.email}'
    
    @login.user_loader
    def load_user(id):
        return User.query.get(int(id))
    

class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    task_name = db.Column(db.String(200))
    due_date = db.Column(db.DateTime())
    status = db.Column(db.String(200))
    todo_owner = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self) -> str:
        return f'Task {self.task_name}{self.due_date}'
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, PasswordField,SelectField, DateField, SubmitField
from wtforms.validators import DataRequired


class TodoForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    due_date = DateField('Due Date', validators=[DataRequired()])
    status = SelectField('Status', choices=[('Complete', 'Complete'), ('Not Started', 'Not Started ')])
    submit = SubmitField('Add Task')

class EditTodoForm(FlaskForm):
    task_name = StringField('Name', validators=[DataRequired()])
    due_date = DateField('Due Date', validators=[DataRequired()])
    status = SelectField('Status', choices=[('COMPLETED', 'COMPLETED'), ('NOTSTARTED', 'NOTSTARTED')])
    submit = SubmitField('Edit Task')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_migrate import Migrate


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
bootstrap = Bootstrap()



def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.api import bp as api_bp
    app.register_blueprint(api_bp,url_prefix='/api')

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)
    
    return app

from app import models

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api',__name__)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app import db
from flask import request, render_template, redirect, flash, url_for, abort
from app.main import bp
from app.models import User, Task
from flask_login import current_user, login_required
from app.main.forms import TodoForm, EditTodoForm

@bp.route('/index', methods=['GET','PUT'])
@bp.route('/', methods=['GET','PUT'])
def index():
    return render_template('index.html')


@bp.route('/add_todo',  methods=["POST","GET"])
@login_required
def add_task():
    form = TodoForm()
    if request.method == "GET":
        return render_template('add_todo.html', form=form)
    if request.method == "POST":
        user = current_user
        if form.validate_on_submit:
            todo = Task(
                task_name = form.name.data,
                due_date = form.due_date.data,
                status = form.status.data,
                todo_owner = user.id
            )
        db.session.add(todo)
        db.session.commit()
        return redirect(url_for('main.todos'))
    
@bp.route('/todos', methods=['GET','POST'])
@login_required
def todos():
    todos = Task.query.filter_by(todo_owner=current_user.id)
    return render_template('todos.html', todos=todos)

@bp.route('/edit_task/<int:id>', methods=['POST','GET'])
def edit_task(id):
    user = current_user
    form = EditTodoForm()
    task = Task.query.filter_by(id=id, todo_owner=current_user.id).first()
    print(task)

    if form.validate_on_submit():
        task.task_name = form.task_name.data
        task.due_date = form.due_date.data
        task.status = form.status.data
        db.session.commit()
        return redirect('main.todos')

    elif request.method == "GET":
        form.task_name.data = task.task_name
        form.due_date.data = task.due_date
        form.status.data = task.status
    
    return render_template('edit_todo.html', form=form, user=user)

@bp.route('/delete_task/<int:id>',methods=['GET','POST'])
def delete(id):
    task = Task.query.filter_by(id=id, todo_owner=current_user.id).first_or_404()
    if request.method == 'POST':
        if task:
            db.session.delete(task)
            db.session.commit()
            return redirect(url_for('main.todos'))
        else:
            return 404
    abort(404)

app/templates/add_todo.html
{% extends 'base.html'%}
{% block content%}
<section class="container">
   <div class="row">
      <div class="col">
         <form action="" method="post">
            <p>
               {{ form.name.label }}<br>
               {{ form.name(size =32) }}
            </p>
            <p>
               {{ form.due_date.label }}<br>
               {{ form.due_date(size=32) }}
            </p>
            <p>
               {{ form.status.label }}<br>
               {{ form.status() }}
            </p>
            <p>{{ form.submit() }}</p>
         </form>
      </div>
   </div>
</section>
{% endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
   {% if title %} {{ title }} {% else %} Welcome to To Do list {% endif %}
{% endblock %}
  <style>
    body {
    font-family: 'Roboto', sans-serif;
    font-weight: 300;
    }
    header {
    padding: 20px 0;
    }
    header .row {
    display: flex;
    align-items: center;
    }
    header h1 {
    font-weight: 700;
    margin: 0;
    color: blue;
    }
    header nav {
    display: flex;
    justify-content: flex-end;
    }
    header p {
    padding: 0 20px;
    margin: 0;
    color: blue;
    }
  
  </style>
{% block navbar %}
<header class="container-fluid">
   <div class="row">
      <h1 class="col-sm-4">Stay Organised</h1>
      <nav class="col-sm-8 text-right d-inline-block">
         <p class="d-inline-block"><a href="{{ url_for('main.index') }}">Home</a></p>
         {% if current_user.is_anonymous %}
         <p class="d-inline-block"><a href="{{ url_for('auth.login') }}">Login</a></p>
         <p class="d-inline-block"><a href=" {{ url_for('auth.register') }}">Register</a></p>
         {% else %}
         <p class="d-inline-block"><a href="{{ url_for('auth.logout')}} ">Logout</a></p>
         {% endif %}
      </nav>
   </div>
</header>
{% endblock %}


{% block content %}
{% endblock  %}

  

app/templates/delete_task.html
{% extends 'base.html'%}
{% block content%}
<section class="container">
   <div class="row">
      <div class="col">
         <p>{{task_name}}</p>
         <form action='' method="post">
            Are you sure you want to delete this Task
            <input type = "submit" value="Delete">
            <a href='/todos'>Go Back</a>
         </form>
      </div>
   </div>
</section>
{% endblock%}

app/templates/edit_todo.html
{% block content%}
</div>
<section class="container">
   <div class="row">
      <div class="col" a>
         <!-- A column inside a row inside a container! -->
         <form action="" method="post">
            <p>
               {{ form.task_name.label }}<br>
               {{ form.task_name(size =32) }}
            </p>
            <p>
               {{ form.due_date.label }}<br>
               {{ form.due_date(size=32) }}
            </p>
            <p>
               {{ form.status.label }}<br>
               {{ form.status() }}
            </p>
            <p>{{ form.submit() }}</p>
         </form>
      </div>
   </div>
</section>
{% endblock %}

app/templates/index.html
welcome

app/templates/login.html
{% extends 'base.html'%}

{% block content%}
<section class="container">
   <div class="row">
      <div class="col">
         <form action="" method="post">
            <p>
               {{ form.email.label }}<br>
               {{ form.email(size =32) }}
            </p>
            <p>
               {{ form.password.label }}<br>
               {{ form.password(size=32) }}
            </p>
            <p>{{ form.submit() }}</p>
         </form>
      </div>
   </div>
</section>
{% endblock %}

app/templates/register.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}


<section class="container">
    <h1>Registration</h1>
    <div class="row ">
        {{ form.hidden_tag() }}
        <div class="col-xs-6 col-xs-offset-3s">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</section>
{% endblock %}

app/templates/todos.html
{% extends 'base.html'%}
{% block content%}
<section class="container">
   <a href="{{ url_for('main.add_task') }}">
   <button class="add_button ">Add New Task</button>
   </a>
   <div class="row">
      <div class="col" >
         {% for todo in todos %}
         <ul id =round>
            <li>{{todo.task_name}}</li>
            <br>
            <li>{{todo.due_date.strftime('%A,%d,%b,%Y')}}</li>
            <br>
            <li>Status: {{todo.status}}</li>
            <br>
         </ul>
         {% endfor %}
      </div>
   </div>
</section>
{% endblock %}